#:schema node_modules/wrangler/config-schema.json
name = "sublink-new"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "741648a032304adf830332f729ec17de" }
]
